services:
  app:
    container_name: nail-project
    build:
      context: .
      dockerfile: ./build/Dockerfile-localhost
    volumes:
      - .:/app
    ports:
      - "9512:9512"
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DB_NAME=${DATABASE_DB_NAME}

      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_CTAG=${RABBITMQ_CTAG}
      - RABBITMQ_URL=${RABBITMQ_URL}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}

    env_file:
      - .env

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   hostname: rabbitmq
  #   healthcheck:
  #     test: ["CMD", "rabbitmq-diagnostics", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

volumes:
  postgres_data:
