env:
  mode: debug

server:
  port: 9512
  # grpc_port: 5511
  locale: 'en'
  timezone: UTC

database:
  host: localhost
  # host: host.docker.internal
  port: 5432
  username: postgres
  password:
  db_name: nail-db
  network:

rabbitmq:
  schema: amqp
  worker: 2
  # host: host.docker.internal
  host: localhost
  port: 5672
  vhost: /
  username: guest
  password: guest
  ssl: false
  ctag: nail-project
  retry: 3
  exchanges: ex.direct.delay
  queue: {}
  uri: amqp://guest:guest@rabbitmq:5672

redis:
  # host: host.docker.internal
  host: localhost
  port: 6379
  password:
  db: 0

jwt:
  secret: your-secret-key
  access_token_expiration_min: 60
  refresh_token_expiration_day: 7
  expiration_hours: 1440