definitions:
  staff.Staff:
    properties:
      code:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      last_name:
        type: string
      phone:
        type: string
      updated_at:
        type: string
    type: object
  utils.APIResponse:
    properties:
      data: {}
      message:
        type: string
      statusCode:
        type: integer
    type: object
info:
  contact: {}
paths:
  /staffs:
    get:
      consumes:
      - application/json
      description: Get list of all staffs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.APIResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/staff.Staff'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.APIResponse'
      summary: Get all staffs
      tags:
      - staffs
    post:
      consumes:
      - application/json
      description: Create a new staff member
      parameters:
      - description: Staff
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/staff.Staff'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/utils.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/staff.Staff'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.APIResponse'
      summary: Create a new staff
      tags:
      - staffs
  /staffs/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a staff member by ID
      parameters:
      - description: Staff ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.APIResponse'
      summary: Delete a staff
      tags:
      - staffs
    put:
      consumes:
      - application/json
      description: Update an existing staff member
      parameters:
      - description: Staff ID
        in: path
        name: id
        required: true
        type: string
      - description: Staff
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/staff.Staff'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/staff.Staff'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.APIResponse'
      summary: Update a staff
      tags:
      - staffs
swagger: "2.0"
